# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo "Connecting to MySQL database..."
    mysql -h TEST-DB-TSTA.0487.P2.TUT.R53.CD2.BP.COM -u SQL_RARG2S -pL#GGFGFY5 -D EPSCLDTSTA -e "SELECT * FROM CURVE_DEFINITIONS WHERE curve_num in (5813);"
  displayName: 'Connect to MySQL Database'
    
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
